project:
  type: website

website:
  title: "Isss608 Coursework"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1"
            file: HandsOnExercise/hands-on-1.qmd
          - text: "Hands-on Exercise 2"
            file: HandsOnExercise/hands-on-2.qmd
          - text: "Hands-on Exercise 3 part I"
            file: HandsOnExercise/hands-on-3-interactive-data.qmd   
          - text: "Hands-on Exercise 3 part II"
            file: HandsOnExercise/hands-on-3-animated-data.qmd 
          - text: "Hands-on Exercise 4 part I"
            file: HandsOnExercise/hands-on-4a.qmd 
          - text: "Hands-on Exercise 4 part II"
            file: HandsOnExercise/hands-on-4b.qmd 
          - text: "Hands-on Exercise 4 part III"
            file: HandsOnExercise/hands-on-4c.qmd 
          - text: "Hands-on Exercise 4 part IV"
            file: HandsOnExercise/hands-on-4d.qmd 
          - text: "Hands-on Exercise 5 part I"
            file: HandsOnExercise/hands-on-5a.qmd 
          - text: "Hands-on Exercise 5 part II"
            file: HandsOnExercise/hands-on-5b.qmd 
          - text: "Hands-on Exercise 5 part III"
            file: HandsOnExercise/hands-on-5c.qmd 
          - text: "Hands-on Exercise 5 part IV"
            file: HandsOnExercise/hands-on-5d.qmd 
          - text: "Hands-on Exercise 5 part V"
            file: HandsOnExercise/hands-on-5e.qmd 
      - href: about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
