project:
  type: website

website:
  title: "Isss608 Coursework"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1"
            file: HandsOnExercise/hands-on-1.qmd
          - text: "Hands-on Exercise 2"
            file: HandsOnExercise/hands-on-2.qmd
          - text: "Hands-on Exercise 3 part I"
            file: HandsOnExercise/hands-on-3-interactive-data.qmd   
          - text: "Hands-on Exercise 3 part II"
            file: HandsOnExercise/hands-on-3-animated-data.qmd 
      - href: about.qmd

format:
  html:
    theme:
      light: [lumen, brand]
    css: styles.css
    toc: true

editor: visual
